// Generated by gencpp from file dynamixel_sdk_examples/GetTorqueResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETTORQUERESPONSE_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETTORQUERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_sdk_examples
{
template <class ContainerAllocator>
struct GetTorqueResponse_
{
  typedef GetTorqueResponse_<ContainerAllocator> Type;

  GetTorqueResponse_()
    : torque(0)  {
    }
  GetTorqueResponse_(const ContainerAllocator& _alloc)
    : torque(0)  {
  (void)_alloc;
    }



   typedef int32_t _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTorqueResponse_

typedef ::dynamixel_sdk_examples::GetTorqueResponse_<std::allocator<void> > GetTorqueResponse;

typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetTorqueResponse > GetTorqueResponsePtr;
typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetTorqueResponse const> GetTorqueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_sdk_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef0ea74b74e0a677f53bfb23f2bf7652";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef0ea74b74e0a677ULL;
  static const uint64_t static_value2 = 0xf53bfb23f2bf7652ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_sdk_examples/GetTorqueResponse";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 torque\n"
"\n"
;
  }

  static const char* value(const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTorqueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_sdk_examples::GetTorqueResponse_<ContainerAllocator>& v)
  {
    s << indent << "torque: ";
    Printer<int32_t>::stream(s, indent + "  ", v.torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETTORQUERESPONSE_H
