// Generated by gencpp from file dynamixel_sdk_examples/GetTorque.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETTORQUE_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETTORQUE_H

#include <ros/service_traits.h>


#include <dynamixel_sdk_examples/GetTorqueRequest.h>
#include <dynamixel_sdk_examples/GetTorqueResponse.h>


namespace dynamixel_sdk_examples
{

struct GetTorque
{

typedef GetTorqueRequest Request;
typedef GetTorqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTorque
} // namespace dynamixel_sdk_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_sdk_examples::GetTorque > {
  static const char* value()
  {
    return "19c4cb65acfb8207353f2423be603ca8";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetTorque&) { return value(); }
};

template<>
struct DataType< ::dynamixel_sdk_examples::GetTorque > {
  static const char* value()
  {
    return "dynamixel_sdk_examples/GetTorque";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetTorque&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetTorqueRequest> should match
// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetTorque >
template<>
struct MD5Sum< ::dynamixel_sdk_examples::GetTorqueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_sdk_examples::GetTorque >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetTorqueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_sdk_examples::GetTorqueRequest> should match
// service_traits::DataType< ::dynamixel_sdk_examples::GetTorque >
template<>
struct DataType< ::dynamixel_sdk_examples::GetTorqueRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_sdk_examples::GetTorque >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetTorqueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetTorqueResponse> should match
// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetTorque >
template<>
struct MD5Sum< ::dynamixel_sdk_examples::GetTorqueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_sdk_examples::GetTorque >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetTorqueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_sdk_examples::GetTorqueResponse> should match
// service_traits::DataType< ::dynamixel_sdk_examples::GetTorque >
template<>
struct DataType< ::dynamixel_sdk_examples::GetTorqueResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_sdk_examples::GetTorque >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetTorqueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETTORQUE_H
